# Workflow for building and deploying a Hugo site with Doks theme to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - "main"  # Triggers deployment on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensures submodules are cloned if your Doks theme uses one

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'
          extended: true  # Ensures extended version of Hugo for SASS support

      - name: Install Dart Sass
        run: npm install -g sass  # Installs Dart Sass using npm

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js dependencies
        run: |
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true  # Installs dependencies if package-lock.json is present

      - name: Clean old build files
        run: |
          rm -rf public/*  # Cleans out old files before building new ones

      - name: Build Hugo Site
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL "https://marcelomamorim.github.io/studying-for-solutions-architect-associate/"  # Sets explicit base URL

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Path to the public folder containing the built site

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
